import { expect, test } from "@playwright/test";
import { ALEX, JORDAN, fillPerson, fixture, hydrated, mockJson } from "./helpers";

/**
 * Screenshot regression tests. Baselines are per platform; only the Linux ones
 * (generated by the "Visual baselines" workflow / CI image) are committed, so a
 * missing baseline on your machine is expected - run `npm run test:e2e:update`
 * locally to create disposable ones.
 *
 * Non-deterministic pixels are masked (the animated star canvas) and CSS
 * animations are fast-forwarded (animations: "disabled" in the config).
 */

const mask = (page: import("@playwright/test").Page) => [page.locator("canvas")];

test("home hero", async ({ page }) => {
  await hydrated(page, "/");
  await page.waitForTimeout(1200); // hero/bar entrance animations
  await expect(page).toHaveScreenshot("home-hero.png", { mask: mask(page) });
});

test("analyze form", async ({ page }) => {
  await hydrated(page, "/analyze/hybrid");
  await expect(page).toHaveScreenshot("analyze-hybrid-form.png", { mask: mask(page) });
});

test("profile page", async ({ page }) => {
  await hydrated(page, "/profile");
  await expect(page).toHaveScreenshot("profile.png", { mask: mask(page) });
});

test("synastry report hero (fixture data)", async ({ page }) => {
  await mockJson(page, "/analyze/full", "full");
  await page.goto("/dashboard");
  await fillPerson(page, 0, ALEX);
  await fillPerson(page, 1, JORDAN);
  await page.getByRole("button", { name: /Generate synastry report/ }).click();
  await expect(page.locator("[data-report]")).toBeVisible({ timeout: 20_000 });

  const overall = fixture<{ relationship_intelligence: { overall_score: number } }>("full").relationship_intelligence.overall_score;
  await expect(page.locator("svg text").first()).toHaveText(overall.toFixed(1), { timeout: 5000 }); // count-up finished
  await page.waitForTimeout(800);
  await expect(page.locator("[data-report] header")).toHaveScreenshot("report-hero.png", { mask: mask(page) });
});

test("command palette", async ({ page }) => {
  await hydrated(page, "/");
  await page.keyboard.press("Control+k");
  await expect(page.getByRole("dialog", { name: "Search" })).toBeVisible();
  await page.waitForTimeout(500);
  await expect(page).toHaveScreenshot("command-palette.png", { mask: mask(page) });
});
