export interface Celebrity {
  name: string
  slug: string
  sign: string        // lowercase: "aries", "taurus", etc.
  born: string        // display format: "Apr 8, 1982"
  birthDay: number
  birthMonth: number
  nationality: string
  category: string    // "Actor", "Musician", "Athlete", etc.
}

export const SIGN_ORDER = [
  "aries","taurus","gemini","cancer","leo","virgo",
  "libra","scorpio","sagittarius","capricorn","aquarius","pisces",
] as const

export const SIGN_SYMBOL: Record<string, string> = {
  aries: "♈", taurus: "♉", gemini: "♊", cancer: "♋",
  leo: "♌", virgo: "♍", libra: "♎", scorpio: "♏",
  sagittarius: "♐", capricorn: "♑", aquarius: "♒", pisces: "♓",
}

export const SIGN_LABEL: Record<string, string> = {
  aries: "Aries", taurus: "Taurus", gemini: "Gemini", cancer: "Cancer",
  leo: "Leo", virgo: "Virgo", libra: "Libra", scorpio: "Scorpio",
  sagittarius: "Sagittarius", capricorn: "Capricorn", aquarius: "Aquarius", pisces: "Pisces",
}

export const SIGN_COLOR: Record<string, string> = {
  aries: "#EF4444", taurus: "#22C55E", gemini: "#EAB308", cancer: "#818CF8",
  leo: "#F97316", virgo: "#84CC16", libra: "#EC4899", scorpio: "#8B5CF6",
  sagittarius: "#F59E0B", capricorn: "#6B7280", aquarius: "#38BDF8", pisces: "#A78BFA",
}

export const CELEBRITIES: Celebrity[] = [
  // ── ARIES ───────────────────────────────────────────────────────────────────
  { name: "Allu Arjun",          slug: "allu-arjun",          sign: "aries", born: "Apr 8, 1982",  birthDay: 8,  birthMonth: 4,  nationality: "Indian",              category: "Actor" },
  { name: "Ram Charan",          slug: "ram-charan",          sign: "aries", born: "Mar 27, 1985", birthDay: 27, birthMonth: 3,  nationality: "Indian",              category: "Actor" },
  { name: "Rashmika Mandanna",   slug: "rashmika-mandanna",   sign: "aries", born: "Apr 5, 1996",  birthDay: 5,  birthMonth: 4,  nationality: "Indian",              category: "Actress" },
  { name: "Ajay Devgn",          slug: "ajay-devgn",          sign: "aries", born: "Apr 2, 1969",  birthDay: 2,  birthMonth: 4,  nationality: "Indian",              category: "Actor" },
  { name: "Rani Mukerji",        slug: "rani-mukerji",        sign: "aries", born: "Mar 21, 1978", birthDay: 21, birthMonth: 3,  nationality: "Indian",              category: "Actress" },
  { name: "Lady Gaga",           slug: "lady-gaga",           sign: "aries", born: "Mar 28, 1986", birthDay: 28, birthMonth: 3,  nationality: "American",            category: "Musician" },
  { name: "Mariah Carey",        slug: "mariah-carey",        sign: "aries", born: "Mar 27, 1969", birthDay: 27, birthMonth: 3,  nationality: "American",            category: "Musician" },
  { name: "Robert Downey Jr.",   slug: "robert-downey-jr",    sign: "aries", born: "Apr 4, 1965",  birthDay: 4,  birthMonth: 4,  nationality: "American",            category: "Actor" },
  { name: "Emma Watson",         slug: "emma-watson",         sign: "aries", born: "Apr 15, 1990", birthDay: 15, birthMonth: 4,  nationality: "British",             category: "Actress" },
  { name: "Elton John",          slug: "elton-john",          sign: "aries", born: "Mar 25, 1947", birthDay: 25, birthMonth: 3,  nationality: "British",             category: "Musician" },
  { name: "Victoria Beckham",    slug: "victoria-beckham",    sign: "aries", born: "Apr 17, 1974", birthDay: 17, birthMonth: 4,  nationality: "British",             category: "Fashion Designer" },
  { name: "Reese Witherspoon",   slug: "reese-witherspoon",   sign: "aries", born: "Mar 22, 1976", birthDay: 22, birthMonth: 3,  nationality: "American",            category: "Actress" },
  { name: "Kristen Stewart",     slug: "kristen-stewart",     sign: "aries", born: "Apr 9, 1990",  birthDay: 9,  birthMonth: 4,  nationality: "American",            category: "Actress" },
  { name: "Jackie Chan",         slug: "jackie-chan",          sign: "aries", born: "Apr 7, 1954",  birthDay: 7,  birthMonth: 4,  nationality: "Chinese",             category: "Actor" },
  { name: "Celine Dion",         slug: "celine-dion",         sign: "aries", born: "Mar 30, 1968", birthDay: 30, birthMonth: 3,  nationality: "Canadian",            category: "Musician" },
  { name: "Pharrell Williams",   slug: "pharrell-williams",   sign: "aries", born: "Apr 5, 1973",  birthDay: 5,  birthMonth: 4,  nationality: "American",            category: "Musician" },
  { name: "Heath Ledger",        slug: "heath-ledger",        sign: "aries", born: "Apr 4, 1979",  birthDay: 4,  birthMonth: 4,  nationality: "Australian",          category: "Actor" },
  { name: "Russell Crowe",       slug: "russell-crowe",       sign: "aries", born: "Apr 7, 1964",  birthDay: 7,  birthMonth: 4,  nationality: "Australian",          category: "Actor" },
  { name: "Charlie Chaplin",     slug: "charlie-chaplin",     sign: "aries", born: "Apr 16, 1889", birthDay: 16, birthMonth: 4,  nationality: "British",             category: "Actor" },
  { name: "Vincent van Gogh",    slug: "vincent-van-gogh",    sign: "aries", born: "Mar 30, 1853", birthDay: 30, birthMonth: 3,  nationality: "Dutch",               category: "Artist" },
  { name: "Keira Knightley",     slug: "keira-knightley",     sign: "aries", born: "Mar 26, 1985", birthDay: 26, birthMonth: 3,  nationality: "British",             category: "Actress" },
  { name: "Quentin Tarantino",   slug: "quentin-tarantino",   sign: "aries", born: "Mar 27, 1963", birthDay: 27, birthMonth: 3,  nationality: "American",            category: "Director" },
  { name: "Paul Rudd",           slug: "paul-rudd",           sign: "aries", born: "Apr 6, 1969",  birthDay: 6,  birthMonth: 4,  nationality: "American",            category: "Actor" },
  { name: "Jennifer Garner",     slug: "jennifer-garner",     sign: "aries", born: "Apr 17, 1972", birthDay: 17, birthMonth: 4,  nationality: "American",            category: "Actress" },
  { name: "Kourtney Kardashian", slug: "kourtney-kardashian", sign: "aries", born: "Apr 18, 1979", birthDay: 18, birthMonth: 4,  nationality: "American",            category: "TV Personality" },
  { name: "Big Sean",            slug: "big-sean",            sign: "aries", born: "Mar 25, 1988", birthDay: 25, birthMonth: 3,  nationality: "American",            category: "Musician" },
  { name: "Chance the Rapper",   slug: "chance-the-rapper",   sign: "aries", born: "Apr 16, 1993", birthDay: 16, birthMonth: 4,  nationality: "American",            category: "Musician" },
  { name: "Conan O'Brien",       slug: "conan-obrien",        sign: "aries", born: "Apr 18, 1963", birthDay: 18, birthMonth: 4,  nationality: "American",            category: "TV Host" },
  { name: "Mandy Moore",         slug: "mandy-moore",         sign: "aries", born: "Apr 10, 1984", birthDay: 10, birthMonth: 4,  nationality: "American",            category: "Actress" },
  { name: "Harry Houdini",       slug: "harry-houdini",       sign: "aries", born: "Mar 24, 1874", birthDay: 24, birthMonth: 3,  nationality: "Hungarian-American",  category: "Illusionist" },

  // ── TAURUS ──────────────────────────────────────────────────────────────────
  { name: "Jr NTR",              slug: "jr-ntr",              sign: "taurus", born: "May 20, 1983", birthDay: 20, birthMonth: 5,  nationality: "Indian",    category: "Actor" },
  { name: "Samantha Ruth Prabhu",slug: "samantha-ruth-prabhu",sign: "taurus", born: "Apr 28, 1987", birthDay: 28, birthMonth: 4,  nationality: "Indian",    category: "Actress" },
  { name: "Ajith Kumar",         slug: "ajith-kumar",         sign: "taurus", born: "May 1, 1971",  birthDay: 1,  birthMonth: 5,  nationality: "Indian",    category: "Actor" },
  { name: "Trisha Krishnan",     slug: "trisha-krishnan",     sign: "taurus", born: "May 4, 1983",  birthDay: 4,  birthMonth: 5,  nationality: "Indian",    category: "Actress" },
  { name: "Anushka Sharma",      slug: "anushka-sharma",      sign: "taurus", born: "May 1, 1988",  birthDay: 1,  birthMonth: 5,  nationality: "Indian",    category: "Actress" },
  { name: "Madhuri Dixit",       slug: "madhuri-dixit",       sign: "taurus", born: "May 15, 1967", birthDay: 15, birthMonth: 5,  nationality: "Indian",    category: "Actress" },
  { name: "Varun Dhawan",        slug: "varun-dhawan",        sign: "taurus", born: "Apr 24, 1987", birthDay: 24, birthMonth: 4,  nationality: "Indian",    category: "Actor" },
  { name: "Dwayne Johnson",      slug: "dwayne-johnson",      sign: "taurus", born: "May 2, 1972",  birthDay: 2,  birthMonth: 5,  nationality: "American",  category: "Actor" },
  { name: "Adele",               slug: "adele",               sign: "taurus", born: "May 5, 1988",  birthDay: 5,  birthMonth: 5,  nationality: "British",   category: "Musician" },
  { name: "Megan Fox",           slug: "megan-fox",           sign: "taurus", born: "May 16, 1986", birthDay: 16, birthMonth: 5,  nationality: "American",  category: "Actress" },
  { name: "George Clooney",      slug: "george-clooney",      sign: "taurus", born: "May 6, 1961",  birthDay: 6,  birthMonth: 5,  nationality: "American",  category: "Actor" },
  { name: "Penélope Cruz",       slug: "penelope-cruz",       sign: "taurus", born: "Apr 28, 1974", birthDay: 28, birthMonth: 4,  nationality: "Spanish",   category: "Actress" },
  { name: "Channing Tatum",      slug: "channing-tatum",      sign: "taurus", born: "Apr 26, 1980", birthDay: 26, birthMonth: 4,  nationality: "American",  category: "Actor" },
  { name: "David Beckham",       slug: "david-beckham",       sign: "taurus", born: "May 2, 1975",  birthDay: 2,  birthMonth: 5,  nationality: "British",   category: "Athlete" },
  { name: "Gal Gadot",           slug: "gal-gadot",           sign: "taurus", born: "Apr 30, 1985", birthDay: 30, birthMonth: 4,  nationality: "Israeli",   category: "Actress" },
  { name: "Lizzo",               slug: "lizzo",               sign: "taurus", born: "Apr 27, 1988", birthDay: 27, birthMonth: 4,  nationality: "American",  category: "Musician" },
  { name: "Henry Cavill",        slug: "henry-cavill",        sign: "taurus", born: "May 5, 1983",  birthDay: 5,  birthMonth: 5,  nationality: "British",   category: "Actor" },
  { name: "Rami Malek",          slug: "rami-malek",          sign: "taurus", born: "May 12, 1981", birthDay: 12, birthMonth: 5,  nationality: "American",  category: "Actor" },
  { name: "Jessica Alba",        slug: "jessica-alba",        sign: "taurus", born: "Apr 28, 1981", birthDay: 28, birthMonth: 4,  nationality: "American",  category: "Actress" },
  { name: "Uma Thurman",         slug: "uma-thurman",         sign: "taurus", born: "Apr 29, 1970", birthDay: 29, birthMonth: 4,  nationality: "American",  category: "Actress" },
  { name: "Robert Pattinson",    slug: "robert-pattinson",    sign: "taurus", born: "May 13, 1986", birthDay: 13, birthMonth: 5,  nationality: "British",   category: "Actor" },
  { name: "Audrey Hepburn",      slug: "audrey-hepburn",      sign: "taurus", born: "May 4, 1929",  birthDay: 4,  birthMonth: 5,  nationality: "Belgian-British", category: "Actress" },
  { name: "Cher",                slug: "cher",                sign: "taurus", born: "May 20, 1946", birthDay: 20, birthMonth: 5,  nationality: "American",  category: "Musician" },
  { name: "Janet Jackson",       slug: "janet-jackson",       sign: "taurus", born: "May 16, 1966", birthDay: 16, birthMonth: 5,  nationality: "American",  category: "Musician" },
  { name: "William Shakespeare", slug: "william-shakespeare", sign: "taurus", born: "Apr 23, 1564", birthDay: 23, birthMonth: 4,  nationality: "British",   category: "Playwright" },
  { name: "Stevie Wonder",       slug: "stevie-wonder",       sign: "taurus", born: "May 13, 1950", birthDay: 13, birthMonth: 5,  nationality: "American",  category: "Musician" },
  { name: "Al Pacino",           slug: "al-pacino",           sign: "taurus", born: "Apr 25, 1940", birthDay: 25, birthMonth: 4,  nationality: "American",  category: "Actor" },
  { name: "Sigmund Freud",       slug: "sigmund-freud",       sign: "taurus", born: "May 6, 1856",  birthDay: 6,  birthMonth: 5,  nationality: "Austrian",  category: "Scientist" },
  { name: "Mark Zuckerberg",     slug: "mark-zuckerberg",     sign: "taurus", born: "May 14, 1984", birthDay: 14, birthMonth: 5,  nationality: "American",  category: "Entrepreneur" },
  { name: "James McAvoy",        slug: "james-mcavoy",        sign: "taurus", born: "Apr 21, 1979", birthDay: 21, birthMonth: 4,  nationality: "Scottish",  category: "Actor" },

  // ── GEMINI ──────────────────────────────────────────────────────────────────
  { name: "Sonam Kapoor",        slug: "sonam-kapoor",        sign: "gemini", born: "Jun 9, 1985",  birthDay: 9,  birthMonth: 6,  nationality: "Indian",    category: "Actress" },
  { name: "Shilpa Shetty",       slug: "shilpa-shetty",       sign: "gemini", born: "Jun 8, 1975",  birthDay: 8,  birthMonth: 6,  nationality: "Indian",    category: "Actress" },
  { name: "Sonakshi Sinha",      slug: "sonakshi-sinha",      sign: "gemini", born: "Jun 2, 1987",  birthDay: 2,  birthMonth: 6,  nationality: "Indian",    category: "Actress" },
  { name: "R Madhavan",          slug: "r-madhavan",          sign: "gemini", born: "Jun 1, 1970",  birthDay: 1,  birthMonth: 6,  nationality: "Indian",    category: "Actor" },
  { name: "Karan Johar",         slug: "karan-johar",         sign: "gemini", born: "May 25, 1972", birthDay: 25, birthMonth: 5,  nationality: "Indian",    category: "Director" },
  { name: "Mithun Chakraborty",  slug: "mithun-chakraborty",  sign: "gemini", born: "Jun 16, 1950", birthDay: 16, birthMonth: 6,  nationality: "Indian",    category: "Actor" },
  { name: "Angelina Jolie",      slug: "angelina-jolie",      sign: "gemini", born: "Jun 4, 1975",  birthDay: 4,  birthMonth: 6,  nationality: "American",  category: "Actress" },
  { name: "Kanye West",          slug: "kanye-west",          sign: "gemini", born: "Jun 8, 1977",  birthDay: 8,  birthMonth: 6,  nationality: "American",  category: "Musician" },
  { name: "Natalie Portman",     slug: "natalie-portman",     sign: "gemini", born: "Jun 9, 1981",  birthDay: 9,  birthMonth: 6,  nationality: "Israeli-American", category: "Actress" },
  { name: "Johnny Depp",         slug: "johnny-depp",         sign: "gemini", born: "Jun 9, 1963",  birthDay: 9,  birthMonth: 6,  nationality: "American",  category: "Actor" },
  { name: "Paul McCartney",      slug: "paul-mccartney",      sign: "gemini", born: "Jun 18, 1942", birthDay: 18, birthMonth: 6,  nationality: "British",   category: "Musician" },
  { name: "Tupac Shakur",        slug: "tupac-shakur",        sign: "gemini", born: "Jun 16, 1971", birthDay: 16, birthMonth: 6,  nationality: "American",  category: "Musician" },
  { name: "Marilyn Monroe",      slug: "marilyn-monroe",      sign: "gemini", born: "Jun 1, 1926",  birthDay: 1,  birthMonth: 6,  nationality: "American",  category: "Actress" },
  { name: "Morgan Freeman",      slug: "morgan-freeman",      sign: "gemini", born: "Jun 1, 1937",  birthDay: 1,  birthMonth: 6,  nationality: "American",  category: "Actor" },
  { name: "Tom Holland",         slug: "tom-holland",         sign: "gemini", born: "Jun 1, 1996",  birthDay: 1,  birthMonth: 6,  nationality: "British",   category: "Actor" },
  { name: "Prince",              slug: "prince",              sign: "gemini", born: "Jun 7, 1958",  birthDay: 7,  birthMonth: 6,  nationality: "American",  category: "Musician" },
  { name: "Venus Williams",      slug: "venus-williams",      sign: "gemini", born: "Jun 17, 1980", birthDay: 17, birthMonth: 6,  nationality: "American",  category: "Athlete" },
  { name: "Awkwafina",           slug: "awkwafina",           sign: "gemini", born: "Jun 2, 1988",  birthDay: 2,  birthMonth: 6,  nationality: "American",  category: "Musician/Actress" },
  { name: "Zoe Saldana",         slug: "zoe-saldana",         sign: "gemini", born: "Jun 19, 1978", birthDay: 19, birthMonth: 6,  nationality: "American",  category: "Actress" },
  { name: "Helena Bonham Carter",slug: "helena-bonham-carter",sign: "gemini", born: "May 26, 1966", birthDay: 26, birthMonth: 5,  nationality: "British",   category: "Actress" },
  { name: "Laverne Cox",         slug: "laverne-cox",         sign: "gemini", born: "May 29, 1972", birthDay: 29, birthMonth: 5,  nationality: "American",  category: "Actress" },
  { name: "Bob Dylan",           slug: "bob-dylan",           sign: "gemini", born: "May 24, 1941", birthDay: 24, birthMonth: 5,  nationality: "American",  category: "Musician" },
  { name: "Kendrick Lamar",      slug: "kendrick-lamar",      sign: "gemini", born: "Jun 17, 1987", birthDay: 17, birthMonth: 6,  nationality: "American",  category: "Musician" },
  { name: "Naomi Campbell",      slug: "naomi-campbell",      sign: "gemini", born: "May 22, 1970", birthDay: 22, birthMonth: 5,  nationality: "British",   category: "Model" },
  { name: "Chris Evans",         slug: "chris-evans",         sign: "gemini", born: "Jun 13, 1981", birthDay: 13, birthMonth: 6,  nationality: "American",  category: "Actor" },
  { name: "Nicole Kidman",       slug: "nicole-kidman",       sign: "gemini", born: "Jun 20, 1967", birthDay: 20, birthMonth: 6,  nationality: "Australian", category: "Actress" },
  { name: "Colin Farrell",       slug: "colin-farrell",       sign: "gemini", born: "May 31, 1976", birthDay: 31, birthMonth: 5,  nationality: "Irish",     category: "Actor" },
  { name: "Walt Whitman",        slug: "walt-whitman",        sign: "gemini", born: "May 31, 1819", birthDay: 31, birthMonth: 5,  nationality: "American",  category: "Poet" },
  { name: "Courteney Cox",       slug: "courteney-cox",       sign: "gemini", born: "Jun 15, 1964", birthDay: 15, birthMonth: 6,  nationality: "American",  category: "Actress" },
  { name: "Iggy Azalea",         slug: "iggy-azalea",         sign: "gemini", born: "Jun 7, 1990",  birthDay: 7,  birthMonth: 6,  nationality: "Australian", category: "Musician" },

  // ── CANCER ──────────────────────────────────────────────────────────────────
  { name: "Priyanka Chopra",     slug: "priyanka-chopra",     sign: "cancer", born: "Jul 18, 1982", birthDay: 18, birthMonth: 7,  nationality: "Indian",          category: "Actress" },
  { name: "Katrina Kaif",        slug: "katrina-kaif",        sign: "cancer", born: "Jul 16, 1983", birthDay: 16, birthMonth: 7,  nationality: "British-Indian",  category: "Actress" },
  { name: "Ranveer Singh",       slug: "ranveer-singh",       sign: "cancer", born: "Jul 6, 1985",  birthDay: 6,  birthMonth: 7,  nationality: "Indian",          category: "Actor" },
  { name: "MS Dhoni",            slug: "ms-dhoni",            sign: "cancer", born: "Jul 7, 1981",  birthDay: 7,  birthMonth: 7,  nationality: "Indian",          category: "Athlete" },
  { name: "Vijay",               slug: "vijay-actor",         sign: "cancer", born: "Jun 22, 1974", birthDay: 22, birthMonth: 6,  nationality: "Indian",          category: "Actor" },
  { name: "Sundar Pichai",       slug: "sundar-pichai",       sign: "cancer", born: "Jul 12, 1972", birthDay: 12, birthMonth: 7,  nationality: "Indian-American", category: "Entrepreneur" },
  { name: "Tom Hanks",           slug: "tom-hanks",           sign: "cancer", born: "Jul 9, 1956",  birthDay: 9,  birthMonth: 7,  nationality: "American",        category: "Actor" },
  { name: "Tom Cruise",          slug: "tom-cruise",          sign: "cancer", born: "Jul 3, 1962",  birthDay: 3,  birthMonth: 7,  nationality: "American",        category: "Actor" },
  { name: "Ariana Grande",       slug: "ariana-grande",       sign: "cancer", born: "Jun 26, 1993", birthDay: 26, birthMonth: 6,  nationality: "American",        category: "Musician" },
  { name: "Selena Gomez",        slug: "selena-gomez",        sign: "cancer", born: "Jul 22, 1992", birthDay: 22, birthMonth: 7,  nationality: "American",        category: "Musician" },
  { name: "Lana Del Rey",        slug: "lana-del-rey",        sign: "cancer", born: "Jun 21, 1985", birthDay: 21, birthMonth: 6,  nationality: "American",        category: "Musician" },
  { name: "Princess Diana",      slug: "princess-diana",      sign: "cancer", born: "Jul 1, 1961",  birthDay: 1,  birthMonth: 7,  nationality: "British",         category: "Royalty" },
  { name: "Elon Musk",           slug: "elon-musk",           sign: "cancer", born: "Jun 28, 1971", birthDay: 28, birthMonth: 6,  nationality: "South African-American", category: "Entrepreneur" },
  { name: "Vin Diesel",          slug: "vin-diesel",          sign: "cancer", born: "Jul 18, 1967", birthDay: 18, birthMonth: 7,  nationality: "American",        category: "Actor" },
  { name: "Kevin Hart",          slug: "kevin-hart",          sign: "cancer", born: "Jul 6, 1979",  birthDay: 6,  birthMonth: 7,  nationality: "American",        category: "Comedian" },
  { name: "Harrison Ford",       slug: "harrison-ford",       sign: "cancer", born: "Jul 13, 1942", birthDay: 13, birthMonth: 7,  nationality: "American",        category: "Actor" },
  { name: "Benedict Cumberbatch",slug: "benedict-cumberbatch",sign: "cancer", born: "Jul 19, 1976", birthDay: 19, birthMonth: 7,  nationality: "British",         category: "Actor" },
  { name: "Meryl Streep",        slug: "meryl-streep",        sign: "cancer", born: "Jun 22, 1949", birthDay: 22, birthMonth: 6,  nationality: "American",        category: "Actress" },
  { name: "Robin Williams",      slug: "robin-williams",      sign: "cancer", born: "Jul 21, 1951", birthDay: 21, birthMonth: 7,  nationality: "American",        category: "Comedian" },
  { name: "Margot Robbie",       slug: "margot-robbie",       sign: "cancer", born: "Jul 2, 1990",  birthDay: 2,  birthMonth: 7,  nationality: "Australian",      category: "Actress" },
  { name: "Post Malone",         slug: "post-malone",         sign: "cancer", born: "Jul 4, 1995",  birthDay: 4,  birthMonth: 7,  nationality: "American",        category: "Musician" },
  { name: "Chris Pratt",         slug: "chris-pratt",         sign: "cancer", born: "Jun 21, 1979", birthDay: 21, birthMonth: 6,  nationality: "American",        category: "Actor" },
  { name: "Jessica Simpson",     slug: "jessica-simpson",     sign: "cancer", born: "Jul 10, 1980", birthDay: 10, birthMonth: 7,  nationality: "American",        category: "Musician" },
  { name: "Tobey Maguire",       slug: "tobey-maguire",       sign: "cancer", born: "Jun 27, 1975", birthDay: 27, birthMonth: 6,  nationality: "American",        category: "Actor" },
  { name: "Nelson Mandela",      slug: "nelson-mandela",      sign: "cancer", born: "Jul 18, 1918", birthDay: 18, birthMonth: 7,  nationality: "South African",   category: "Political Leader" },
  { name: "Franz Kafka",         slug: "franz-kafka",         sign: "cancer", born: "Jul 3, 1883",  birthDay: 3,  birthMonth: 7,  nationality: "Czech",           category: "Author" },
  { name: "Ringo Starr",         slug: "ringo-starr",         sign: "cancer", born: "Jul 7, 1940",  birthDay: 7,  birthMonth: 7,  nationality: "British",         category: "Musician" },
  { name: "Khloe Kardashian",    slug: "khloe-kardashian",    sign: "cancer", born: "Jun 27, 1984", birthDay: 27, birthMonth: 6,  nationality: "American",        category: "TV Personality" },
  { name: "Diane Kruger",        slug: "diane-kruger",        sign: "cancer", born: "Jul 15, 1976", birthDay: 15, birthMonth: 7,  nationality: "German",          category: "Actress" },
  { name: "Pamela Anderson",     slug: "pamela-anderson",     sign: "cancer", born: "Jul 1, 1967",  birthDay: 1,  birthMonth: 7,  nationality: "Canadian",        category: "Actress" },

  // ── LEO ─────────────────────────────────────────────────────────────────────
  { name: "Mahesh Babu",         slug: "mahesh-babu",         sign: "leo", born: "Aug 9, 1975",  birthDay: 9,  birthMonth: 8,  nationality: "Indian",    category: "Actor" },
  { name: "Chiranjeevi",         slug: "chiranjeevi",         sign: "leo", born: "Aug 22, 1955", birthDay: 22, birthMonth: 8,  nationality: "Indian",    category: "Actor" },
  { name: "Suriya",              slug: "suriya",              sign: "leo", born: "Jul 23, 1975", birthDay: 23, birthMonth: 7,  nationality: "Indian",    category: "Actor" },
  { name: "Dhanush",             slug: "dhanush",             sign: "leo", born: "Jul 28, 1983", birthDay: 28, birthMonth: 7,  nationality: "Indian",    category: "Actor" },
  { name: "Kajol",               slug: "kajol",               sign: "leo", born: "Aug 5, 1974",  birthDay: 5,  birthMonth: 8,  nationality: "Indian",    category: "Actress" },
  { name: "Satya Nadella",       slug: "satya-nadella",       sign: "leo", born: "Aug 10, 1967", birthDay: 10, birthMonth: 8,  nationality: "Indian-American", category: "Entrepreneur" },
  { name: "Barack Obama",        slug: "barack-obama",        sign: "leo", born: "Aug 4, 1961",  birthDay: 4,  birthMonth: 8,  nationality: "American",  category: "Politician" },
  { name: "Jennifer Lopez",      slug: "jennifer-lopez",      sign: "leo", born: "Jul 24, 1969", birthDay: 24, birthMonth: 7,  nationality: "American",  category: "Musician" },
  { name: "Madonna",             slug: "madonna",             sign: "leo", born: "Aug 16, 1958", birthDay: 16, birthMonth: 8,  nationality: "American",  category: "Musician" },
  { name: "Demi Lovato",         slug: "demi-lovato",         sign: "leo", born: "Aug 20, 1992", birthDay: 20, birthMonth: 8,  nationality: "American",  category: "Musician" },
  { name: "Kylie Jenner",        slug: "kylie-jenner",        sign: "leo", born: "Aug 10, 1997", birthDay: 10, birthMonth: 8,  nationality: "American",  category: "Entrepreneur" },
  { name: "Chris Hemsworth",     slug: "chris-hemsworth",     sign: "leo", born: "Aug 11, 1983", birthDay: 11, birthMonth: 8,  nationality: "Australian", category: "Actor" },
  { name: "Daniel Radcliffe",    slug: "daniel-radcliffe",    sign: "leo", born: "Jul 23, 1989", birthDay: 23, birthMonth: 7,  nationality: "British",   category: "Actor" },
  { name: "Mick Jagger",         slug: "mick-jagger",         sign: "leo", born: "Jul 26, 1943", birthDay: 26, birthMonth: 7,  nationality: "British",   category: "Musician" },
  { name: "Roger Federer",       slug: "roger-federer",       sign: "leo", born: "Aug 8, 1981",  birthDay: 8,  birthMonth: 8,  nationality: "Swiss",     category: "Athlete" },
  { name: "Ben Affleck",         slug: "ben-affleck",         sign: "leo", born: "Aug 15, 1972", birthDay: 15, birthMonth: 8,  nationality: "American",  category: "Actor" },
  { name: "Sandra Bullock",      slug: "sandra-bullock",      sign: "leo", born: "Jul 26, 1964", birthDay: 26, birthMonth: 7,  nationality: "American",  category: "Actress" },
  { name: "Robert De Niro",      slug: "robert-de-niro",      sign: "leo", born: "Aug 17, 1943", birthDay: 17, birthMonth: 8,  nationality: "American",  category: "Actor" },
  { name: "Bill Clinton",        slug: "bill-clinton",        sign: "leo", born: "Aug 19, 1946", birthDay: 19, birthMonth: 8,  nationality: "American",  category: "Politician" },
  { name: "Andy Warhol",         slug: "andy-warhol",         sign: "leo", born: "Aug 6, 1928",  birthDay: 6,  birthMonth: 8,  nationality: "American",  category: "Artist" },
  { name: "Whitney Houston",     slug: "whitney-houston",     sign: "leo", born: "Aug 9, 1963",  birthDay: 9,  birthMonth: 8,  nationality: "American",  category: "Musician" },
  { name: "Tom Brady",           slug: "tom-brady",           sign: "leo", born: "Aug 3, 1977",  birthDay: 3,  birthMonth: 8,  nationality: "American",  category: "Athlete" },
  { name: "Halle Berry",         slug: "halle-berry",         sign: "leo", born: "Aug 14, 1966", birthDay: 14, birthMonth: 8,  nationality: "American",  category: "Actress" },
  { name: "Antonio Banderas",    slug: "antonio-banderas",    sign: "leo", born: "Aug 10, 1960", birthDay: 10, birthMonth: 8,  nationality: "Spanish",   category: "Actor" },
  { name: "Anna Kendrick",       slug: "anna-kendrick",       sign: "leo", born: "Aug 9, 1985",  birthDay: 9,  birthMonth: 8,  nationality: "American",  category: "Actress" },
  { name: "Dustin Hoffman",      slug: "dustin-hoffman",      sign: "leo", born: "Aug 8, 1937",  birthDay: 8,  birthMonth: 8,  nationality: "American",  category: "Actor" },
  { name: "Coco Chanel",         slug: "coco-chanel",         sign: "leo", born: "Aug 19, 1883", birthDay: 19, birthMonth: 8,  nationality: "French",    category: "Fashion Designer" },
  { name: "Jason Momoa",         slug: "jason-momoa",         sign: "leo", born: "Aug 1, 1979",  birthDay: 1,  birthMonth: 8,  nationality: "American",  category: "Actor" },
  { name: "Viola Davis",         slug: "viola-davis",         sign: "leo", born: "Aug 11, 1965", birthDay: 11, birthMonth: 8,  nationality: "American",  category: "Actress" },
  { name: "Shawn Mendes",        slug: "shawn-mendes",        sign: "leo", born: "Aug 8, 1998",  birthDay: 8,  birthMonth: 8,  nationality: "Canadian",  category: "Musician" },

  // ── VIRGO ───────────────────────────────────────────────────────────────────
  { name: "Kareena Kapoor",      slug: "kareena-kapoor",      sign: "virgo", born: "Sep 21, 1980", birthDay: 21, birthMonth: 9,  nationality: "Indian",    category: "Actress" },
  { name: "Akshay Kumar",        slug: "akshay-kumar",        sign: "virgo", born: "Sep 9, 1967",  birthDay: 9,  birthMonth: 9,  nationality: "Indian",    category: "Actor" },
  { name: "Nagarjuna",           slug: "nagarjuna",           sign: "virgo", born: "Aug 29, 1959", birthDay: 29, birthMonth: 8,  nationality: "Indian",    category: "Actor" },
  { name: "Pawan Kalyan",        slug: "pawan-kalyan",        sign: "virgo", born: "Sep 2, 1971",  birthDay: 2,  birthMonth: 9,  nationality: "Indian",    category: "Actor" },
  { name: "Simbu",               slug: "simbu",               sign: "virgo", born: "Sep 2, 1983",  birthDay: 2,  birthMonth: 9,  nationality: "Indian",    category: "Actor" },
  { name: "Rishi Kapoor",        slug: "rishi-kapoor",        sign: "virgo", born: "Sep 4, 1952",  birthDay: 4,  birthMonth: 9,  nationality: "Indian",    category: "Actor" },
  { name: "Beyoncé",             slug: "beyonce",             sign: "virgo", born: "Sep 4, 1981",  birthDay: 4,  birthMonth: 9,  nationality: "American",  category: "Musician" },
  { name: "Michael Jackson",     slug: "michael-jackson",     sign: "virgo", born: "Aug 29, 1958", birthDay: 29, birthMonth: 8,  nationality: "American",  category: "Musician" },
  { name: "Keanu Reeves",        slug: "keanu-reeves",        sign: "virgo", born: "Sep 2, 1964",  birthDay: 2,  birthMonth: 9,  nationality: "Canadian",  category: "Actor" },
  { name: "Zendaya",             slug: "zendaya",             sign: "virgo", born: "Sep 1, 2002",  birthDay: 1,  birthMonth: 9,  nationality: "American",  category: "Actress" },
  { name: "Nick Jonas",          slug: "nick-jonas",          sign: "virgo", born: "Sep 16, 1992", birthDay: 16, birthMonth: 9,  nationality: "American",  category: "Musician" },
  { name: "Tim Burton",          slug: "tim-burton",          sign: "virgo", born: "Aug 25, 1958", birthDay: 25, birthMonth: 8,  nationality: "American",  category: "Director" },
  { name: "Taraji P. Henson",    slug: "taraji-p-henson",     sign: "virgo", born: "Sep 11, 1970", birthDay: 11, birthMonth: 9,  nationality: "American",  category: "Actress" },
  { name: "Blake Lively",        slug: "blake-lively",        sign: "virgo", born: "Aug 25, 1987", birthDay: 25, birthMonth: 8,  nationality: "American",  category: "Actress" },
  { name: "Cameron Diaz",        slug: "cameron-diaz",        sign: "virgo", born: "Aug 30, 1972", birthDay: 30, birthMonth: 8,  nationality: "American",  category: "Actress" },
  { name: "Salma Hayek",         slug: "salma-hayek",         sign: "virgo", born: "Sep 2, 1966",  birthDay: 2,  birthMonth: 9,  nationality: "Mexican",   category: "Actress" },
  { name: "Adam Sandler",        slug: "adam-sandler",        sign: "virgo", born: "Sep 9, 1966",  birthDay: 9,  birthMonth: 9,  nationality: "American",  category: "Comedian" },
  { name: "Freddie Mercury",     slug: "freddie-mercury",     sign: "virgo", born: "Sep 5, 1946",  birthDay: 5,  birthMonth: 9,  nationality: "British",   category: "Musician" },
  { name: "Mother Teresa",       slug: "mother-teresa",       sign: "virgo", born: "Aug 26, 1910", birthDay: 26, birthMonth: 8,  nationality: "Albanian-Indian", category: "Humanitarian" },
  { name: "Stephen King",        slug: "stephen-king",        sign: "virgo", born: "Sep 21, 1947", birthDay: 21, birthMonth: 9,  nationality: "American",  category: "Author" },
  { name: "Amy Winehouse",       slug: "amy-winehouse",       sign: "virgo", born: "Sep 14, 1983", birthDay: 14, birthMonth: 9,  nationality: "British",   category: "Musician" },
  { name: "Pink",                slug: "pink",                sign: "virgo", born: "Sep 8, 1979",  birthDay: 8,  birthMonth: 9,  nationality: "American",  category: "Musician" },
  { name: "Jimmy Fallon",        slug: "jimmy-fallon",        sign: "virgo", born: "Sep 19, 1974", birthDay: 19, birthMonth: 9,  nationality: "American",  category: "TV Host" },
  { name: "Sophia Loren",        slug: "sophia-loren",        sign: "virgo", born: "Sep 20, 1934", birthDay: 20, birthMonth: 9,  nationality: "Italian",   category: "Actress" },
  { name: "Leo Tolstoy",         slug: "leo-tolstoy",         sign: "virgo", born: "Sep 9, 1828",  birthDay: 9,  birthMonth: 9,  nationality: "Russian",   category: "Author" },
  { name: "Macaulay Culkin",     slug: "macaulay-culkin",     sign: "virgo", born: "Aug 26, 1980", birthDay: 26, birthMonth: 8,  nationality: "American",  category: "Actor" },
  { name: "Claudia Schiffer",    slug: "claudia-schiffer",    sign: "virgo", born: "Aug 25, 1970", birthDay: 25, birthMonth: 8,  nationality: "German",    category: "Model" },
  { name: "Charlie Sheen",       slug: "charlie-sheen",       sign: "virgo", born: "Sep 3, 1965",  birthDay: 3,  birthMonth: 9,  nationality: "American",  category: "Actor" },
  { name: "Shania Twain",        slug: "shania-twain",        sign: "virgo", born: "Aug 28, 1965", birthDay: 28, birthMonth: 8,  nationality: "Canadian",  category: "Musician" },
  { name: "Chris Pine",          slug: "chris-pine",          sign: "virgo", born: "Aug 26, 1980", birthDay: 26, birthMonth: 8,  nationality: "American",  category: "Actor" },

  // ── LIBRA ───────────────────────────────────────────────────────────────────
  { name: "Amitabh Bachchan",    slug: "amitabh-bachchan",    sign: "libra", born: "Oct 11, 1942", birthDay: 11, birthMonth: 10, nationality: "Indian",          category: "Actor" },
  { name: "Rekha",               slug: "rekha",               sign: "libra", born: "Oct 10, 1954", birthDay: 10, birthMonth: 10, nationality: "Indian",          category: "Actress" },
  { name: "Ranbir Kapoor",       slug: "ranbir-kapoor",       sign: "libra", born: "Sep 28, 1982", birthDay: 28, birthMonth: 9,  nationality: "Indian",          category: "Actor" },
  { name: "Hardik Pandya",       slug: "hardik-pandya",       sign: "libra", born: "Oct 11, 1993", birthDay: 11, birthMonth: 10, nationality: "Indian",          category: "Athlete" },
  { name: "Rishabh Pant",        slug: "rishabh-pant",        sign: "libra", born: "Oct 4, 1997",  birthDay: 4,  birthMonth: 10, nationality: "Indian",          category: "Athlete" },
  { name: "Pooja Hegde",         slug: "pooja-hegde",         sign: "libra", born: "Oct 13, 1990", birthDay: 13, birthMonth: 10, nationality: "Indian",          category: "Actress" },
  { name: "Rakul Preet Singh",   slug: "rakul-preet-singh",   sign: "libra", born: "Oct 10, 1990", birthDay: 10, birthMonth: 10, nationality: "Indian",          category: "Actress" },
  { name: "Kim Kardashian",      slug: "kim-kardashian",      sign: "libra", born: "Oct 21, 1980", birthDay: 21, birthMonth: 10, nationality: "American",        category: "TV Personality" },
  { name: "Will Smith",          slug: "will-smith",          sign: "libra", born: "Sep 25, 1968", birthDay: 25, birthMonth: 9,  nationality: "American",        category: "Actor" },
  { name: "Eminem",              slug: "eminem",              sign: "libra", born: "Oct 17, 1972", birthDay: 17, birthMonth: 10, nationality: "American",        category: "Musician" },
  { name: "Cardi B",             slug: "cardi-b",             sign: "libra", born: "Oct 11, 1992", birthDay: 11, birthMonth: 10, nationality: "American",        category: "Musician" },
  { name: "Zac Efron",           slug: "zac-efron",           sign: "libra", born: "Oct 18, 1987", birthDay: 18, birthMonth: 10, nationality: "American",        category: "Actor" },
  { name: "Gwyneth Paltrow",     slug: "gwyneth-paltrow",     sign: "libra", born: "Sep 27, 1972", birthDay: 27, birthMonth: 9,  nationality: "American",        category: "Actress" },
  { name: "Kate Winslet",        slug: "kate-winslet",        sign: "libra", born: "Oct 5, 1975",  birthDay: 5,  birthMonth: 10, nationality: "British",         category: "Actress" },
  { name: "John Lennon",         slug: "john-lennon",         sign: "libra", born: "Oct 9, 1940",  birthDay: 9,  birthMonth: 10, nationality: "British",         category: "Musician" },
  { name: "Bruno Mars",          slug: "bruno-mars",          sign: "libra", born: "Oct 8, 1985",  birthDay: 8,  birthMonth: 10, nationality: "American",        category: "Musician" },
  { name: "Snoop Dogg",          slug: "snoop-dogg",          sign: "libra", born: "Oct 20, 1971", birthDay: 20, birthMonth: 10, nationality: "American",        category: "Musician" },
  { name: "Oscar Wilde",         slug: "oscar-wilde",         sign: "libra", born: "Oct 16, 1854", birthDay: 16, birthMonth: 10, nationality: "Irish",           category: "Author" },
  { name: "F. Scott Fitzgerald", slug: "f-scott-fitzgerald",  sign: "libra", born: "Sep 24, 1896", birthDay: 24, birthMonth: 9,  nationality: "American",        category: "Author" },
  { name: "Serena Williams",     slug: "serena-williams",     sign: "libra", born: "Sep 26, 1981", birthDay: 26, birthMonth: 9,  nationality: "American",        category: "Athlete" },
  { name: "Usher",               slug: "usher",               sign: "libra", born: "Oct 14, 1978", birthDay: 14, birthMonth: 10, nationality: "American",        category: "Musician" },
  { name: "Bella Hadid",         slug: "bella-hadid",         sign: "libra", born: "Oct 9, 1996",  birthDay: 9,  birthMonth: 10, nationality: "Palestinian-American", category: "Model" },
  { name: "Matt Damon",          slug: "matt-damon",          sign: "libra", born: "Oct 8, 1970",  birthDay: 8,  birthMonth: 10, nationality: "American",        category: "Actor" },
  { name: "Hilary Duff",         slug: "hilary-duff",         sign: "libra", born: "Sep 28, 1987", birthDay: 28, birthMonth: 9,  nationality: "American",        category: "Actress" },
  { name: "Naomi Watts",         slug: "naomi-watts",         sign: "libra", born: "Sep 28, 1968", birthDay: 28, birthMonth: 9,  nationality: "British-Australian", category: "Actress" },
  { name: "Doja Cat",            slug: "doja-cat",            sign: "libra", born: "Oct 21, 1995", birthDay: 21, birthMonth: 10, nationality: "American",        category: "Musician" },
  { name: "Catherine Zeta-Jones",slug: "catherine-zeta-jones",sign: "libra", born: "Sep 25, 1969", birthDay: 25, birthMonth: 9,  nationality: "Welsh",           category: "Actress" },
  { name: "Mahatma Gandhi",      slug: "mahatma-gandhi",      sign: "libra", born: "Oct 2, 1869",  birthDay: 2,  birthMonth: 10, nationality: "Indian",          category: "Political Leader" },
  { name: "Sacha Baron Cohen",   slug: "sacha-baron-cohen",   sign: "libra", born: "Oct 13, 1971", birthDay: 13, birthMonth: 10, nationality: "British",         category: "Comedian" },
  { name: "Viggo Mortensen",     slug: "viggo-mortensen",     sign: "libra", born: "Oct 20, 1958", birthDay: 20, birthMonth: 10, nationality: "Danish-American", category: "Actor" },

  // ── SCORPIO ─────────────────────────────────────────────────────────────────
  { name: "Shah Rukh Khan",      slug: "shah-rukh-khan",      sign: "scorpio", born: "Nov 2, 1965",  birthDay: 2,  birthMonth: 11, nationality: "Indian",    category: "Actor" },
  { name: "Aishwarya Rai",       slug: "aishwarya-rai",       sign: "scorpio", born: "Nov 1, 1973",  birthDay: 1,  birthMonth: 11, nationality: "Indian",    category: "Actress" },
  { name: "Virat Kohli",         slug: "virat-kohli",         sign: "scorpio", born: "Nov 5, 1988",  birthDay: 5,  birthMonth: 11, nationality: "Indian",    category: "Athlete" },
  { name: "Prabhas",             slug: "prabhas",             sign: "scorpio", born: "Oct 23, 1979", birthDay: 23, birthMonth: 10, nationality: "Indian",    category: "Actor" },
  { name: "Kamal Haasan",        slug: "kamal-haasan",        sign: "scorpio", born: "Nov 7, 1954",  birthDay: 7,  birthMonth: 11, nationality: "Indian",    category: "Actor" },
  { name: "Nayanthara",          slug: "nayanthara",          sign: "scorpio", born: "Nov 18, 1984", birthDay: 18, birthMonth: 11, nationality: "Indian",    category: "Actress" },
  { name: "Anushka Shetty",      slug: "anushka-shetty",      sign: "scorpio", born: "Nov 7, 1984",  birthDay: 7,  birthMonth: 11, nationality: "Indian",    category: "Actress" },
  { name: "Indira Gandhi",       slug: "indira-gandhi",       sign: "scorpio", born: "Nov 19, 1917", birthDay: 19, birthMonth: 11, nationality: "Indian",    category: "Political Leader" },
  { name: "Jawaharlal Nehru",    slug: "jawaharlal-nehru",    sign: "scorpio", born: "Nov 14, 1889", birthDay: 14, birthMonth: 11, nationality: "Indian",    category: "Political Leader" },
  { name: "Leonardo DiCaprio",   slug: "leonardo-dicaprio",   sign: "scorpio", born: "Nov 11, 1974", birthDay: 11, birthMonth: 11, nationality: "American",  category: "Actor" },
  { name: "Ryan Gosling",        slug: "ryan-gosling",        sign: "scorpio", born: "Nov 12, 1980", birthDay: 12, birthMonth: 11, nationality: "Canadian",  category: "Actor" },
  { name: "Katy Perry",          slug: "katy-perry",          sign: "scorpio", born: "Oct 25, 1984", birthDay: 25, birthMonth: 10, nationality: "American",  category: "Musician" },
  { name: "Gabrielle Union",     slug: "gabrielle-union",     sign: "scorpio", born: "Oct 29, 1972", birthDay: 29, birthMonth: 10, nationality: "American",  category: "Actress" },
  { name: "Drake",               slug: "drake",               sign: "scorpio", born: "Oct 24, 1986", birthDay: 24, birthMonth: 10, nationality: "Canadian",  category: "Musician" },
  { name: "Hillary Clinton",     slug: "hillary-clinton",     sign: "scorpio", born: "Oct 26, 1947", birthDay: 26, birthMonth: 10, nationality: "American",  category: "Politician" },
  { name: "Julia Roberts",       slug: "julia-roberts",       sign: "scorpio", born: "Oct 28, 1967", birthDay: 28, birthMonth: 10, nationality: "American",  category: "Actress" },
  { name: "Matthew McConaughey", slug: "matthew-mcconaughey", sign: "scorpio", born: "Nov 4, 1969",  birthDay: 4,  birthMonth: 11, nationality: "American",  category: "Actor" },
  { name: "Whoopi Goldberg",     slug: "whoopi-goldberg",     sign: "scorpio", born: "Nov 13, 1955", birthDay: 13, birthMonth: 11, nationality: "American",  category: "Comedian" },
  { name: "Anne Hathaway",       slug: "anne-hathaway",       sign: "scorpio", born: "Nov 12, 1982", birthDay: 12, birthMonth: 11, nationality: "American",  category: "Actress" },
  { name: "Pablo Picasso",       slug: "pablo-picasso",       sign: "scorpio", born: "Oct 25, 1881", birthDay: 25, birthMonth: 10, nationality: "Spanish",   category: "Artist" },
  { name: "Bill Gates",          slug: "bill-gates",          sign: "scorpio", born: "Oct 28, 1955", birthDay: 28, birthMonth: 10, nationality: "American",  category: "Entrepreneur" },
  { name: "Winona Ryder",        slug: "winona-ryder",        sign: "scorpio", born: "Oct 29, 1971", birthDay: 29, birthMonth: 10, nationality: "American",  category: "Actress" },
  { name: "Adam Driver",         slug: "adam-driver",         sign: "scorpio", born: "Nov 19, 1983", birthDay: 19, birthMonth: 11, nationality: "American",  category: "Actor" },
  { name: "Calvin Klein",        slug: "calvin-klein",        sign: "scorpio", born: "Nov 19, 1942", birthDay: 19, birthMonth: 11, nationality: "American",  category: "Fashion Designer" },
  { name: "Jodie Foster",        slug: "jodie-foster",        sign: "scorpio", born: "Nov 19, 1962", birthDay: 19, birthMonth: 11, nationality: "American",  category: "Actress" },
  { name: "Frank Ocean",         slug: "frank-ocean",         sign: "scorpio", born: "Oct 28, 1987", birthDay: 28, birthMonth: 10, nationality: "American",  category: "Musician" },
  { name: "Owen Wilson",         slug: "owen-wilson",         sign: "scorpio", born: "Nov 18, 1968", birthDay: 18, birthMonth: 11, nationality: "American",  category: "Actor" },
  { name: "Condoleezza Rice",    slug: "condoleezza-rice",    sign: "scorpio", born: "Nov 14, 1954", birthDay: 14, birthMonth: 11, nationality: "American",  category: "Politician" },
  { name: "Björk",               slug: "bjork",               sign: "scorpio", born: "Nov 21, 1965", birthDay: 21, birthMonth: 11, nationality: "Icelandic", category: "Musician" },
  { name: "Penn Badgley",        slug: "penn-badgley",        sign: "scorpio", born: "Nov 1, 1986",  birthDay: 1,  birthMonth: 11, nationality: "American",  category: "Actor" },

  // ── SAGITTARIUS ─────────────────────────────────────────────────────────────
  { name: "Rajinikanth",         slug: "rajinikanth",         sign: "sagittarius", born: "Dec 12, 1950", birthDay: 12, birthMonth: 12, nationality: "Indian",              category: "Actor" },
  { name: "Jasprit Bumrah",      slug: "jasprit-bumrah",      sign: "sagittarius", born: "Dec 6, 1993",  birthDay: 6,  birthMonth: 12, nationality: "Indian",              category: "Athlete" },
  { name: "Kartik Aaryan",       slug: "kartik-aaryan",       sign: "sagittarius", born: "Nov 22, 1990", birthDay: 22, birthMonth: 11, nationality: "Indian",              category: "Actor" },
  { name: "Tamannaah Bhatia",    slug: "tamannaah-bhatia",    sign: "sagittarius", born: "Dec 21, 1989", birthDay: 21, birthMonth: 12, nationality: "Indian",              category: "Actress" },
  { name: "Naga Chaitanya",      slug: "naga-chaitanya",      sign: "sagittarius", born: "Nov 23, 1984", birthDay: 23, birthMonth: 11, nationality: "Indian",              category: "Actor" },
  { name: "Riteish Deshmukh",    slug: "riteish-deshmukh",    sign: "sagittarius", born: "Dec 17, 1978", birthDay: 17, birthMonth: 12, nationality: "Indian",              category: "Actor" },
  { name: "Scarlett Johansson",  slug: "scarlett-johansson",  sign: "sagittarius", born: "Nov 22, 1984", birthDay: 22, birthMonth: 11, nationality: "American",            category: "Actress" },
  { name: "Taylor Swift",        slug: "taylor-swift",        sign: "sagittarius", born: "Dec 13, 1989", birthDay: 13, birthMonth: 12, nationality: "American",            category: "Musician" },
  { name: "Brad Pitt",           slug: "brad-pitt",           sign: "sagittarius", born: "Dec 18, 1963", birthDay: 18, birthMonth: 12, nationality: "American",            category: "Actor" },
  { name: "Miley Cyrus",         slug: "miley-cyrus",         sign: "sagittarius", born: "Nov 23, 1992", birthDay: 23, birthMonth: 11, nationality: "American",            category: "Musician" },
  { name: "Britney Spears",      slug: "britney-spears",      sign: "sagittarius", born: "Dec 2, 1981",  birthDay: 2,  birthMonth: 12, nationality: "American",            category: "Musician" },
  { name: "Jay-Z",               slug: "jay-z",               sign: "sagittarius", born: "Dec 4, 1969",  birthDay: 4,  birthMonth: 12, nationality: "American",            category: "Musician" },
  { name: "Winston Churchill",   slug: "winston-churchill",   sign: "sagittarius", born: "Nov 30, 1874", birthDay: 30, birthMonth: 11, nationality: "British",             category: "Political Leader" },
  { name: "Bruce Lee",           slug: "bruce-lee",           sign: "sagittarius", born: "Nov 27, 1940", birthDay: 27, birthMonth: 11, nationality: "Hong Kong-American",  category: "Martial Artist" },
  { name: "Walt Disney",         slug: "walt-disney",         sign: "sagittarius", born: "Dec 5, 1901",  birthDay: 5,  birthMonth: 12, nationality: "American",            category: "Entrepreneur" },
  { name: "Frank Sinatra",       slug: "frank-sinatra",       sign: "sagittarius", born: "Dec 12, 1915", birthDay: 12, birthMonth: 12, nationality: "American",            category: "Musician" },
  { name: "Nicki Minaj",         slug: "nicki-minaj",         sign: "sagittarius", born: "Dec 8, 1982",  birthDay: 8,  birthMonth: 12, nationality: "Trinidadian-American", category: "Musician" },
  { name: "Jamie Foxx",          slug: "jamie-foxx",          sign: "sagittarius", born: "Dec 13, 1967", birthDay: 13, birthMonth: 12, nationality: "American",            category: "Musician" },
  { name: "Jake Gyllenhaal",     slug: "jake-gyllenhaal",     sign: "sagittarius", born: "Dec 19, 1980", birthDay: 19, birthMonth: 12, nationality: "American",            category: "Actor" },
  { name: "Tina Turner",         slug: "tina-turner",         sign: "sagittarius", born: "Nov 26, 1939", birthDay: 26, birthMonth: 11, nationality: "American",            category: "Musician" },
  { name: "Steven Spielberg",    slug: "steven-spielberg",    sign: "sagittarius", born: "Dec 18, 1946", birthDay: 18, birthMonth: 12, nationality: "American",            category: "Director" },
  { name: "Ben Stiller",         slug: "ben-stiller",         sign: "sagittarius", born: "Nov 30, 1965", birthDay: 30, birthMonth: 11, nationality: "American",            category: "Comedian" },
  { name: "Tyra Banks",          slug: "tyra-banks",          sign: "sagittarius", born: "Dec 4, 1973",  birthDay: 4,  birthMonth: 12, nationality: "American",            category: "Model" },
  { name: "DJ Khaled",           slug: "dj-khaled",           sign: "sagittarius", born: "Nov 26, 1975", birthDay: 26, birthMonth: 11, nationality: "Palestinian-American", category: "Musician" },
  { name: "Billie Eilish",       slug: "billie-eilish",       sign: "sagittarius", born: "Dec 18, 2001", birthDay: 18, birthMonth: 12, nationality: "American",            category: "Musician" },
  { name: "Jimi Hendrix",        slug: "jimi-hendrix",        sign: "sagittarius", born: "Nov 27, 1942", birthDay: 27, birthMonth: 11, nationality: "American",            category: "Musician" },
  { name: "Mark Twain",          slug: "mark-twain",          sign: "sagittarius", born: "Nov 30, 1835", birthDay: 30, birthMonth: 11, nationality: "American",            category: "Author" },
  { name: "Ludwig van Beethoven",slug: "ludwig-van-beethoven",sign: "sagittarius", born: "Dec 17, 1770", birthDay: 17, birthMonth: 12, nationality: "German",              category: "Musician" },
  { name: "Samuel L. Jackson",   slug: "samuel-l-jackson",    sign: "sagittarius", born: "Dec 21, 1948", birthDay: 21, birthMonth: 12, nationality: "American",            category: "Actor" },
  { name: "Jim Morrison",        slug: "jim-morrison",        sign: "sagittarius", born: "Dec 8, 1943",  birthDay: 8,  birthMonth: 12, nationality: "American",            category: "Musician" },

  // ── CAPRICORN ───────────────────────────────────────────────────────────────
  { name: "Salman Khan",         slug: "salman-khan",         sign: "capricorn", born: "Dec 27, 1965", birthDay: 27, birthMonth: 12, nationality: "Indian",         category: "Actor" },
  { name: "Deepika Padukone",    slug: "deepika-padukone",    sign: "capricorn", born: "Jan 5, 1986",  birthDay: 5,  birthMonth: 1,  nationality: "Indian",         category: "Actress" },
  { name: "Hrithik Roshan",      slug: "hrithik-roshan",      sign: "capricorn", born: "Jan 10, 1974", birthDay: 10, birthMonth: 1,  nationality: "Indian",         category: "Actor" },
  { name: "AR Rahman",           slug: "ar-rahman",           sign: "capricorn", born: "Jan 6, 1967",  birthDay: 6,  birthMonth: 1,  nationality: "Indian",         category: "Musician" },
  { name: "Vijay Sethupathi",    slug: "vijay-sethupathi",    sign: "capricorn", born: "Jan 16, 1978", birthDay: 16, birthMonth: 1,  nationality: "Indian",         category: "Actor" },
  { name: "Ratan Tata",          slug: "ratan-tata",          sign: "capricorn", born: "Dec 28, 1937", birthDay: 28, birthMonth: 12, nationality: "Indian",         category: "Entrepreneur" },
  { name: "Irrfan Khan",         slug: "irrfan-khan",         sign: "capricorn", born: "Jan 7, 1967",  birthDay: 7,  birthMonth: 1,  nationality: "Indian",         category: "Actor" },
  { name: "LeBron James",        slug: "lebron-james",        sign: "capricorn", born: "Dec 30, 1984", birthDay: 30, birthMonth: 12, nationality: "American",       category: "Athlete" },
  { name: "Michelle Obama",      slug: "michelle-obama",      sign: "capricorn", born: "Jan 17, 1964", birthDay: 17, birthMonth: 1,  nationality: "American",       category: "Politician" },
  { name: "Bradley Cooper",      slug: "bradley-cooper",      sign: "capricorn", born: "Jan 5, 1975",  birthDay: 5,  birthMonth: 1,  nationality: "American",       category: "Actor" },
  { name: "Kate Middleton",      slug: "kate-middleton",      sign: "capricorn", born: "Jan 9, 1982",  birthDay: 9,  birthMonth: 1,  nationality: "British",        category: "Royalty" },
  { name: "Dolly Parton",        slug: "dolly-parton",        sign: "capricorn", born: "Jan 19, 1946", birthDay: 19, birthMonth: 1,  nationality: "American",       category: "Musician" },
  { name: "Zayn Malik",          slug: "zayn-malik",          sign: "capricorn", born: "Jan 12, 1993", birthDay: 12, birthMonth: 1,  nationality: "British",        category: "Musician" },
  { name: "John Legend",         slug: "john-legend",         sign: "capricorn", born: "Dec 28, 1978", birthDay: 28, birthMonth: 12, nationality: "American",       category: "Musician" },
  { name: "Mel Gibson",          slug: "mel-gibson",          sign: "capricorn", born: "Jan 3, 1956",  birthDay: 3,  birthMonth: 1,  nationality: "American-Australian", category: "Actor" },
  { name: "Jared Leto",          slug: "jared-leto",          sign: "capricorn", born: "Dec 26, 1971", birthDay: 26, birthMonth: 12, nationality: "American",       category: "Musician" },
  { name: "Liam Hemsworth",      slug: "liam-hemsworth",      sign: "capricorn", born: "Jan 13, 1990", birthDay: 13, birthMonth: 1,  nationality: "Australian",     category: "Actor" },
  { name: "Nicolas Cage",        slug: "nicolas-cage",        sign: "capricorn", born: "Jan 7, 1964",  birthDay: 7,  birthMonth: 1,  nationality: "American",       category: "Actor" },
  { name: "Jeff Bezos",          slug: "jeff-bezos",          sign: "capricorn", born: "Jan 12, 1964", birthDay: 12, birthMonth: 1,  nationality: "American",       category: "Entrepreneur" },
  { name: "David Bowie",         slug: "david-bowie",         sign: "capricorn", born: "Jan 8, 1947",  birthDay: 8,  birthMonth: 1,  nationality: "British",        category: "Musician" },
  { name: "Timothée Chalamet",   slug: "timothee-chalamet",   sign: "capricorn", born: "Dec 27, 2000", birthDay: 27, birthMonth: 12, nationality: "American-French", category: "Actor" },
  { name: "Denzel Washington",   slug: "denzel-washington",   sign: "capricorn", born: "Dec 28, 1954", birthDay: 28, birthMonth: 12, nationality: "American",       category: "Actor" },
  { name: "Lin-Manuel Miranda",  slug: "lin-manuel-miranda",  sign: "capricorn", born: "Jan 16, 1980", birthDay: 16, birthMonth: 1,  nationality: "American",       category: "Musician" },
  { name: "Diane Keaton",        slug: "diane-keaton",        sign: "capricorn", born: "Jan 5, 1946",  birthDay: 5,  birthMonth: 1,  nationality: "American",       category: "Actress" },
  { name: "Mary J. Blige",       slug: "mary-j-blige",        sign: "capricorn", born: "Jan 11, 1971", birthDay: 11, birthMonth: 1,  nationality: "American",       category: "Musician" },
  { name: "Jim Carrey",          slug: "jim-carrey",          sign: "capricorn", born: "Jan 17, 1962", birthDay: 17, birthMonth: 1,  nationality: "Canadian",       category: "Comedian" },
  { name: "Cary Grant",          slug: "cary-grant",          sign: "capricorn", born: "Jan 18, 1904", birthDay: 18, birthMonth: 1,  nationality: "British-American", category: "Actor" },
  { name: "Stephen Hawking",     slug: "stephen-hawking",     sign: "capricorn", born: "Jan 8, 1942",  birthDay: 8,  birthMonth: 1,  nationality: "British",        category: "Scientist" },
  { name: "Elvis Presley",       slug: "elvis-presley",       sign: "capricorn", born: "Jan 8, 1935",  birthDay: 8,  birthMonth: 1,  nationality: "American",       category: "Musician" },
  { name: "Edgar Allan Poe",     slug: "edgar-allan-poe",     sign: "capricorn", born: "Jan 19, 1809", birthDay: 19, birthMonth: 1,  nationality: "American",       category: "Author" },

  // ── AQUARIUS ────────────────────────────────────────────────────────────────
  { name: "Preity Zinta",        slug: "preity-zinta",        sign: "aquarius", born: "Jan 31, 1974", birthDay: 31, birthMonth: 1,  nationality: "Indian",      category: "Actress" },
  { name: "Abhishek Bachchan",   slug: "abhishek-bachchan",   sign: "aquarius", born: "Feb 5, 1976",  birthDay: 5,  birthMonth: 2,  nationality: "Indian",      category: "Actor" },
  { name: "Bobby Deol",          slug: "bobby-deol",          sign: "aquarius", born: "Jan 27, 1969", birthDay: 27, birthMonth: 1,  nationality: "Indian",      category: "Actor" },
  { name: "Tovino Thomas",       slug: "tovino-thomas",       sign: "aquarius", born: "Jan 21, 1989", birthDay: 21, birthMonth: 1,  nationality: "Indian",      category: "Actor" },
  { name: "Sophie Choudry",      slug: "sophie-choudry",      sign: "aquarius", born: "Jan 20, 1981", birthDay: 20, birthMonth: 1,  nationality: "Indian",      category: "Musician" },
  { name: "Pooja Batt",          slug: "pooja-batt",          sign: "aquarius", born: "Feb 11, 1972", birthDay: 11, birthMonth: 2,  nationality: "Indian",      category: "Actress" },
  { name: "Oprah Winfrey",       slug: "oprah-winfrey",       sign: "aquarius", born: "Jan 29, 1954", birthDay: 29, birthMonth: 1,  nationality: "American",    category: "TV Host" },
  { name: "Jennifer Aniston",    slug: "jennifer-aniston",    sign: "aquarius", born: "Feb 11, 1969", birthDay: 11, birthMonth: 2,  nationality: "American",    category: "Actress" },
  { name: "The Weeknd",          slug: "the-weeknd",          sign: "aquarius", born: "Feb 16, 1990", birthDay: 16, birthMonth: 2,  nationality: "Canadian",    category: "Musician" },
  { name: "Harry Styles",        slug: "harry-styles",        sign: "aquarius", born: "Feb 1, 1994",  birthDay: 1,  birthMonth: 2,  nationality: "British",     category: "Musician" },
  { name: "Ellen DeGeneres",     slug: "ellen-degeneres",     sign: "aquarius", born: "Jan 26, 1958", birthDay: 26, birthMonth: 1,  nationality: "American",    category: "TV Host" },
  { name: "Alicia Keys",         slug: "alicia-keys",         sign: "aquarius", born: "Jan 25, 1981", birthDay: 25, birthMonth: 1,  nationality: "American",    category: "Musician" },
  { name: "Michael Jordan",      slug: "michael-jordan",      sign: "aquarius", born: "Feb 17, 1963", birthDay: 17, birthMonth: 2,  nationality: "American",    category: "Athlete" },
  { name: "Shakira",             slug: "shakira",             sign: "aquarius", born: "Feb 2, 1977",  birthDay: 2,  birthMonth: 2,  nationality: "Colombian",   category: "Musician" },
  { name: "Ed Sheeran",          slug: "ed-sheeran",          sign: "aquarius", born: "Feb 17, 1991", birthDay: 17, birthMonth: 2,  nationality: "British",     category: "Musician" },
  { name: "Christian Bale",      slug: "christian-bale",      sign: "aquarius", born: "Jan 30, 1974", birthDay: 30, birthMonth: 1,  nationality: "British",     category: "Actor" },
  { name: "Justin Timberlake",   slug: "justin-timberlake",   sign: "aquarius", born: "Jan 31, 1981", birthDay: 31, birthMonth: 1,  nationality: "American",    category: "Musician" },
  { name: "Paris Hilton",        slug: "paris-hilton",        sign: "aquarius", born: "Feb 17, 1981", birthDay: 17, birthMonth: 2,  nationality: "American",    category: "TV Personality" },
  { name: "Bob Marley",          slug: "bob-marley",          sign: "aquarius", born: "Feb 6, 1945",  birthDay: 6,  birthMonth: 2,  nationality: "Jamaican",    category: "Musician" },
  { name: "Rosa Parks",          slug: "rosa-parks",          sign: "aquarius", born: "Feb 4, 1913",  birthDay: 4,  birthMonth: 2,  nationality: "American",    category: "Activist" },
  { name: "Abraham Lincoln",     slug: "abraham-lincoln",     sign: "aquarius", born: "Feb 12, 1809", birthDay: 12, birthMonth: 2,  nationality: "American",    category: "Political Leader" },
  { name: "Charles Darwin",      slug: "charles-darwin",      sign: "aquarius", born: "Feb 12, 1809", birthDay: 12, birthMonth: 2,  nationality: "British",     category: "Scientist" },
  { name: "Galileo Galilei",     slug: "galileo-galilei",     sign: "aquarius", born: "Feb 15, 1564", birthDay: 15, birthMonth: 2,  nationality: "Italian",     category: "Scientist" },
  { name: "Cristiano Ronaldo",   slug: "cristiano-ronaldo",   sign: "aquarius", born: "Feb 5, 1985",  birthDay: 5,  birthMonth: 2,  nationality: "Portuguese",  category: "Athlete" },
  { name: "Isla Fisher",         slug: "isla-fisher",         sign: "aquarius", born: "Feb 3, 1976",  birthDay: 3,  birthMonth: 2,  nationality: "Australian",  category: "Actress" },
  { name: "Kerry Washington",    slug: "kerry-washington",    sign: "aquarius", born: "Jan 31, 1977", birthDay: 31, birthMonth: 1,  nationality: "American",    category: "Actress" },
  { name: "Ashton Kutcher",      slug: "ashton-kutcher",      sign: "aquarius", born: "Feb 7, 1978",  birthDay: 7,  birthMonth: 2,  nationality: "American",    category: "Actor" },
  { name: "Yoko Ono",            slug: "yoko-ono",            sign: "aquarius", born: "Feb 18, 1933", birthDay: 18, birthMonth: 2,  nationality: "Japanese",    category: "Artist" },
  { name: "Tom Selleck",         slug: "tom-selleck",         sign: "aquarius", born: "Jan 29, 1945", birthDay: 29, birthMonth: 1,  nationality: "American",    category: "Actor" },
  { name: "Robbie Williams",     slug: "robbie-williams",     sign: "aquarius", born: "Feb 13, 1974", birthDay: 13, birthMonth: 2,  nationality: "British",     category: "Musician" },

  // ── PISCES ──────────────────────────────────────────────────────────────────
  { name: "Aamir Khan",          slug: "aamir-khan",          sign: "pisces", born: "Mar 14, 1965", birthDay: 14, birthMonth: 3,  nationality: "Indian",          category: "Actor" },
  { name: "Alia Bhatt",          slug: "alia-bhatt",          sign: "pisces", born: "Mar 15, 1993", birthDay: 15, birthMonth: 3,  nationality: "Indian",          category: "Actress" },
  { name: "Tiger Shroff",        slug: "tiger-shroff",        sign: "pisces", born: "Mar 2, 1990",  birthDay: 2,  birthMonth: 3,  nationality: "Indian",          category: "Actor" },
  { name: "Shahid Kapoor",       slug: "shahid-kapoor",       sign: "pisces", born: "Feb 25, 1981", birthDay: 25, birthMonth: 2,  nationality: "Indian",          category: "Actor" },
  { name: "Shraddha Kapoor",     slug: "shraddha-kapoor",     sign: "pisces", born: "Mar 3, 1987",  birthDay: 3,  birthMonth: 3,  nationality: "Indian",          category: "Actress" },
  { name: "Nani",                slug: "nani",                sign: "pisces", born: "Feb 24, 1984", birthDay: 24, birthMonth: 2,  nationality: "Indian",          category: "Actor" },
  { name: "Anupam Kher",         slug: "anupam-kher",         sign: "pisces", born: "Mar 7, 1955",  birthDay: 7,  birthMonth: 3,  nationality: "Indian",          category: "Actor" },
  { name: "Rihanna",             slug: "rihanna",             sign: "pisces", born: "Feb 20, 1988", birthDay: 20, birthMonth: 2,  nationality: "Barbadian",       category: "Musician" },
  { name: "Drew Barrymore",      slug: "drew-barrymore",      sign: "pisces", born: "Feb 22, 1975", birthDay: 22, birthMonth: 2,  nationality: "American",        category: "Actress" },
  { name: "Daniel Craig",        slug: "daniel-craig",        sign: "pisces", born: "Mar 2, 1968",  birthDay: 2,  birthMonth: 3,  nationality: "British",         category: "Actor" },
  { name: "Eva Mendes",          slug: "eva-mendes",          sign: "pisces", born: "Mar 5, 1974",  birthDay: 5,  birthMonth: 3,  nationality: "American",        category: "Actress" },
  { name: "Justin Bieber",       slug: "justin-bieber",       sign: "pisces", born: "Mar 1, 1994",  birthDay: 1,  birthMonth: 3,  nationality: "Canadian",        category: "Musician" },
  { name: "Adam Levine",         slug: "adam-levine",         sign: "pisces", born: "Mar 18, 1979", birthDay: 18, birthMonth: 3,  nationality: "American",        category: "Musician" },
  { name: "Cindy Crawford",      slug: "cindy-crawford",      sign: "pisces", born: "Feb 20, 1966", birthDay: 20, birthMonth: 2,  nationality: "American",        category: "Model" },
  { name: "Eva Longoria",        slug: "eva-longoria",        sign: "pisces", born: "Mar 15, 1975", birthDay: 15, birthMonth: 3,  nationality: "American",        category: "Actress" },
  { name: "Bruce Willis",        slug: "bruce-willis",        sign: "pisces", born: "Mar 19, 1955", birthDay: 19, birthMonth: 3,  nationality: "American",        category: "Actor" },
  { name: "Albert Einstein",     slug: "albert-einstein",     sign: "pisces", born: "Mar 14, 1879", birthDay: 14, birthMonth: 3,  nationality: "German",          category: "Scientist" },
  { name: "Frédéric Chopin",     slug: "frederic-chopin",     sign: "pisces", born: "Mar 1, 1810",  birthDay: 1,  birthMonth: 3,  nationality: "Polish",          category: "Musician" },
  { name: "Steve Jobs",          slug: "steve-jobs",          sign: "pisces", born: "Feb 24, 1955", birthDay: 24, birthMonth: 2,  nationality: "American",        category: "Entrepreneur" },
  { name: "Elizabeth Taylor",    slug: "elizabeth-taylor",    sign: "pisces", born: "Feb 27, 1932", birthDay: 27, birthMonth: 2,  nationality: "British-American", category: "Actress" },
  { name: "Jon Hamm",            slug: "jon-hamm",            sign: "pisces", born: "Mar 10, 1971", birthDay: 10, birthMonth: 3,  nationality: "American",        category: "Actor" },
  { name: "Olivia Rodrigo",      slug: "olivia-rodrigo",      sign: "pisces", born: "Feb 20, 2003", birthDay: 20, birthMonth: 2,  nationality: "American",        category: "Musician" },
  { name: "Emily Blunt",         slug: "emily-blunt",         sign: "pisces", born: "Feb 23, 1983", birthDay: 23, birthMonth: 2,  nationality: "British",         category: "Actress" },
  { name: "Camila Cabello",      slug: "camila-cabello",      sign: "pisces", born: "Mar 3, 1997",  birthDay: 3,  birthMonth: 3,  nationality: "Cuban-American",  category: "Musician" },
  { name: "Rachel Weisz",        slug: "rachel-weisz",        sign: "pisces", born: "Mar 7, 1970",  birthDay: 7,  birthMonth: 3,  nationality: "British",         category: "Actress" },
  { name: "Lupita Nyong'o",      slug: "lupita-nyongo",       sign: "pisces", born: "Mar 1, 1983",  birthDay: 1,  birthMonth: 3,  nationality: "Kenyan-Mexican",  category: "Actress" },
  { name: "Kesha",               slug: "kesha",               sign: "pisces", born: "Mar 1, 1987",  birthDay: 1,  birthMonth: 3,  nationality: "American",        category: "Musician" },
  { name: "George Washington",   slug: "george-washington",   sign: "pisces", born: "Feb 22, 1732", birthDay: 22, birthMonth: 2,  nationality: "American",        category: "Political Leader" },
  { name: "Michelangelo",        slug: "michelangelo",        sign: "pisces", born: "Mar 6, 1475",  birthDay: 6,  birthMonth: 3,  nationality: "Italian",         category: "Artist" },
  { name: "Kurt Cobain",         slug: "kurt-cobain",         sign: "pisces", born: "Feb 20, 1967", birthDay: 20, birthMonth: 2,  nationality: "American",        category: "Musician" },
]

// ── Lookup helpers ───────────────────────────────────────────────────────────

export function getCelebrityBySlug(slug: string): Celebrity | undefined {
  return CELEBRITIES.find(c => c.slug === slug)
}

export function getCelebritiesBySign(sign: string): Celebrity[] {
  return CELEBRITIES.filter(c => c.sign === sign.toLowerCase())
}
