export interface MbtiTypeData {
  type: string;
  nickname: string;
  role: string;
  description: string;
  strengths: string[];
  weaknesses: string[];
  in_love: string;
  as_a_friend: string;
  career: string;
  best_matches: string[];
  famous: string[];
}

export const MBTI_DATA: Record<string, MbtiTypeData> = {
  INTJ: {
    type: "INTJ", nickname: "The Architect", role: "Analyst",
    description: "INTJs are strategic, independent thinkers who see the world through systems and long-term plans. Rare and quietly confident, they combine analytical intelligence with fierce determination. They hold themselves and others to extremely high standards.",
    strengths: ["Strategic long-term thinking","Decisive and self-confident","High standards and discipline","Independent and innovative","Deep intellectual curiosity"],
    weaknesses: ["Can appear arrogant","Overly critical of others","Uncomfortable with emotions","Dislikes inefficiency in others","Difficulty accepting others' methods"],
    in_love: "INTJs approach relationships like projects — they invest deeply once committed. They show love through acts of service and planning, not verbal affection. They need a partner who respects their independence and can match their intellectual depth.",
    as_a_friend: "They have few close friends by design. They prefer depth over breadth and value friends who can keep up intellectually. Loyal to a fault once trust is established.",
    career: "Thrives in roles requiring strategy and systems thinking — engineering, architecture, science, law, finance, and executive leadership.",
    best_matches: ["ENFP","ENTP","INFJ","ENTJ"],
    famous: ["Elon Musk","Christopher Nolan","Nikola Tesla","Friedrich Nietzsche"],
  },
  INTP: {
    type: "INTP", nickname: "The Logician", role: "Analyst",
    description: "INTPs are theoretical innovators driven by pure logic. They're endlessly curious, love exploring abstract ideas, and are often lost in thought. They care less about how things are and more about how they could be.",
    strengths: ["Exceptional analytical mind","Open-minded and objective","Creative and inventive","Enthusiastic about ideas","Honest and straightforward"],
    weaknesses: ["Absent-minded and impractical","Socially awkward at times","Insensitive to emotions","Difficulty with follow-through","Perfectionism blocks completion"],
    in_love: "INTPs tend to be honest and straightforward partners. They show affection through intellectual engagement, sharing ideas, and deep late-night conversations. They need a partner who appreciates their need for alone time.",
    as_a_friend: "Warm but selective. They enjoy friends who debate ideas passionately without taking it personally. Fiercely loyal and the first to help solve a friend's problem.",
    career: "Excels in philosophy, mathematics, computer science, research, writing, and any field that rewards thinking outside the box.",
    best_matches: ["ENTJ","ESTJ","ENFJ","INFJ"],
    famous: ["Albert Einstein","Bill Gates","Charles Darwin","Larry Page"],
  },
  ENTJ: {
    type: "ENTJ", nickname: "The Commander", role: "Analyst",
    description: "ENTJs are born leaders who exude confidence and drive. They see inefficiency as a personal challenge and are naturally drawn to roles of authority. Highly strategic, they build ambitious plans and marshal others to execute them.",
    strengths: ["Natural leadership and charisma","Strategic and decisive","High energy and confidence","Efficient and driven","Direct communicator"],
    weaknesses: ["Intolerant of inefficiency","Domineering at times","Impatient with others","Struggles with vulnerability","Overly focused on goals"],
    in_love: "ENTJs pursue relationships with the same intensity as career goals. They're loyal partners who like to lead and provide. They need a partner who is confident, independent, and can handle direct feedback.",
    as_a_friend: "They're energizing friends who push you to be better. Expect honest, sometimes blunt, feedback. They'll show up when it matters most.",
    career: "Thrives as CEO, entrepreneur, lawyer, executive, military officer, or any leadership-heavy role.",
    best_matches: ["INFP","INTP","ENFP","INTJ"],
    famous: ["Steve Jobs","Margaret Thatcher","Julius Caesar","Gordon Ramsay"],
  },
  ENTP: {
    type: "ENTP", nickname: "The Debater", role: "Analyst",
    description: "ENTPs are endlessly curious and love exploring ideas — especially by arguing every side of them. They're charming, quick-witted, and thrive in environments where creativity and innovation are valued.",
    strengths: ["Quick wit and intelligence","Charismatic and energetic","Loves brainstorming","Excellent at spotting opportunities","Open-minded and adaptable"],
    weaknesses: ["Can be argumentative","Struggles with follow-through","Gets bored easily","Insensitive at times","Dislikes routine"],
    in_love: "ENTPs love the intellectual push-and-pull of a relationship. They want a partner who can keep up with their ideas and challenge them. They're fun, spontaneous partners who struggle with emotional depth early on.",
    as_a_friend: "The life of the group. Always ready with a new idea or controversial opinion. Loyal and energizing to be around.",
    career: "Excels as entrepreneur, lawyer, consultant, inventor, marketer, or comedian.",
    best_matches: ["INFJ","INTJ","ENFJ","INFP"],
    famous: ["Mark Twain","Leonardo da Vinci","Celine Dion","Thomas Edison"],
  },
  INFJ: {
    type: "INFJ", nickname: "The Advocate", role: "Diplomat",
    description: "The rarest personality type. INFJs combine deep empathy with visionary thinking, creating individuals who are both idealistic and surprisingly strategic. They feel deeply, care intensely, and always keep one eye on the future.",
    strengths: ["Deep empathy and insight","Creative and visionary","Principled and determined","Inspiring to others","Excellent listener"],
    weaknesses: ["Prone to burnout","Highly private","Perfectionist tendencies","Avoids confrontation","Can become reclusive"],
    in_love: "INFJs are deeply romantic and devoted. They seek a soulmate-level connection — intellectual, emotional, and spiritual alignment. They show love through deep understanding and quiet devotion.",
    as_a_friend: "Rare but irreplaceable. INFJs remember everything you say and are the friend who truly understands you on a soul level.",
    career: "Thrives as counselor, writer, doctor, psychologist, teacher, artist, or non-profit leader.",
    best_matches: ["ENTP","ENFP","INTJ","INFP"],
    famous: ["Nelson Mandela","Martin Luther King Jr.","Oprah Winfrey","Plato"],
  },
  INFP: {
    type: "INFP", nickname: "The Mediator", role: "Diplomat",
    description: "INFPs are dreamers and idealists guided by deep personal values. Creative, empathetic, and quietly intense, they seek authentic connections and meaning in everything they do.",
    strengths: ["Deep empathy and compassion","Creative and imaginative","Open-minded","Passionate about values","Adaptable and flexible"],
    weaknesses: ["Overly idealistic","Self-isolating under stress","Takes criticism personally","Difficulty with practical matters","Prone to unhealthy people-pleasing"],
    in_love: "INFPs are fiercely devoted partners who idealize relationships. They express love through creativity, words of affirmation, and quality time. They need a partner who respects their emotions and inner world.",
    as_a_friend: "Kind, empathetic, and non-judgmental. The friend who listens for hours and always sees the best in you.",
    career: "Thrives in writing, art, psychology, social work, music, education, and humanitarian work.",
    best_matches: ["ENTJ","ENFJ","INFJ","ENTP"],
    famous: ["William Shakespeare","J.R.R. Tolkien","Audrey Hepburn","Johnny Depp"],
  },
  ENFJ: {
    type: "ENFJ", nickname: "The Protagonist", role: "Diplomat",
    description: "ENFJs are charismatic leaders who inspire others to grow. They're warm, organized, and deeply invested in the well-being of those around them. Natural mentors with magnetic personalities.",
    strengths: ["Charismatic and empathetic","Natural mentor and leader","Organized and determined","Deeply caring","Inspiring communicator"],
    weaknesses: ["Overly idealistic","Too sensitive to criticism","Struggles with personal decisions","Can neglect own needs","Approval-seeking"],
    in_love: "ENFJs are devoted, warm, and romantic partners. They go out of their way to make their partner feel special. They need emotional reciprocity and honest communication.",
    as_a_friend: "The friend everyone wants. Warm, loyal, remembered your birthday two weeks early, and genuinely invested in your growth.",
    career: "Thrives as teacher, coach, HR manager, politician, non-profit leader, or public speaker.",
    best_matches: ["INFP","ISFP","INTP","INTJ"],
    famous: ["Barack Obama","Oprah Winfrey","Martin Luther King Jr.","Jennifer Lawrence"],
  },
  ENFP: {
    type: "ENFP", nickname: "The Campaigner", role: "Diplomat",
    description: "ENFPs are enthusiastic, creative free spirits who see life as full of possibilities. They're warm, charming, and move through the world with infectious energy and genuine curiosity about people.",
    strengths: ["Enthusiastic and creative","Empathetic and warm","Excellent communicator","Open-minded","Charismatic and popular"],
    weaknesses: ["Difficulty focusing","Overly emotional","Dislikes routine","Struggles with follow-through","Approval-seeking"],
    in_love: "ENFPs are passionate, deeply romantic partners. They bring creativity and adventure into relationships. They need a partner who can match their emotional depth and give them the freedom to grow.",
    as_a_friend: "The friend who makes everything feel like an adventure. Always with a new plan, a heartfelt check-in, and total acceptance of who you are.",
    career: "Thrives as journalist, actor, entrepreneur, coach, artist, consultant, or social worker.",
    best_matches: ["INTJ","INFJ","ENFJ","ENTJ"],
    famous: ["Robin Williams","Jennifer Aniston","Will Smith","Mark Twain"],
  },
  ISTJ: {
    type: "ISTJ", nickname: "The Logistician", role: "Sentinel",
    description: "ISTJs are reliable, hardworking, and deeply principled. They build on tradition, honor their commitments, and provide stability in any environment. The bedrock of every team and family.",
    strengths: ["Reliable and responsible","Thorough and detail-oriented","Honest and direct","Patient and calm","Excellent follow-through"],
    weaknesses: ["Rigid and rule-bound","Judgmental at times","Resistant to change","Emotionally reserved","Struggles with imagination"],
    in_love: "ISTJs are loyal, dependable partners who show love through consistent actions over words. They value long-term commitment and take their role as a partner seriously.",
    as_a_friend: "The friend who shows up every time, no matter what. Reliable, grounded, and unfailingly honest.",
    career: "Thrives in accounting, law, military, administration, banking, medicine, and engineering.",
    best_matches: ["ESFP","ESTP","INFP","ENFP"],
    famous: ["George Washington","Warren Buffett","Queen Elizabeth II","Natalie Portman"],
  },
  ISFJ: {
    type: "ISFJ", nickname: "The Defender", role: "Sentinel",
    description: "ISFJs are warm, caring, and deeply dedicated to protecting those they love. They're attentive to details, remember the small things, and quietly create stability for everyone around them.",
    strengths: ["Caring and nurturing","Reliable and patient","Detail-oriented","Excellent memory for people","Loyal and devoted"],
    weaknesses: ["Reluctant to change","Avoids conflict","Overloads themselves","Takes everything personally","Represses own needs"],
    in_love: "ISFJs are deeply devoted and expressive partners. They show love through acts of service and remembering every little detail. They need appreciation and emotional security.",
    as_a_friend: "The friend who remembers your dog's birthday. Warm, attentive, and always ready to help without being asked.",
    career: "Thrives in nursing, teaching, social work, childcare, administration, and counseling.",
    best_matches: ["ESTP","ESFP","ISTJ","ENFJ"],
    famous: ["Mother Teresa","Kate Middleton","Vin Diesel","Beyoncé"],
  },
  ESTJ: {
    type: "ESTJ", nickname: "The Executive", role: "Sentinel",
    description: "ESTJs are organized, rule-following leaders who believe in order, tradition, and responsibility. They're natural managers who get things done efficiently and hold everyone to high standards.",
    strengths: ["Strong leadership","Organized and systematic","Honest and dedicated","Patient and reliable","Community-focused"],
    weaknesses: ["Inflexible about rules","Judgmental","Struggles with emotions","Overly focused on status","Difficulty relaxing"],
    in_love: "ESTJs take relationships seriously. They're loyal, protective partners who provide stability and structure. They need a partner who respects their traditions and shares their values.",
    as_a_friend: "The friend who organizes the group trip, makes the spreadsheet, and makes sure everyone shows up on time.",
    career: "Thrives in management, law, finance, military, politics, and business operations.",
    best_matches: ["ISFP","ISTP","INFP","INTP"],
    famous: ["Michelle Obama","Frank Sinatra","Sonia Sotomayor","Emma Watson"],
  },
  ESFJ: {
    type: "ESFJ", nickname: "The Consul", role: "Sentinel",
    description: "ESFJs are warm, social, and deeply attuned to others' needs. They create harmony wherever they go and take genuine pride in caring for the people in their lives.",
    strengths: ["Warm and caring","Highly organized","Excellent social skills","Loyal and dependable","Strong community ties"],
    weaknesses: ["Needs approval","Inflexible about values","Too self-sacrificing","Sensitive to criticism","Struggles with change"],
    in_love: "ESFJs are devoted, affectionate partners. They pour themselves into relationships and thrive when their love is reciprocated with appreciation and quality time.",
    as_a_friend: "The social glue of any group. They plan everything, remember everyone's preferences, and make every gathering feel warm and special.",
    career: "Thrives in nursing, teaching, social work, event planning, HR, and public relations.",
    best_matches: ["ISFP","ISTP","INFP","ENTP"],
    famous: ["Taylor Swift","Bill Clinton","Danny Glover","Martha Stewart"],
  },
  ISTP: {
    type: "ISTP", nickname: "The Virtuoso", role: "Explorer",
    description: "ISTPs are bold, practical problem-solvers who love hands-on exploration. They're calm under pressure, mechanically gifted, and have a natural ability to figure out how things work.",
    strengths: ["Creative and practical","Calm in crisis","Excellent troubleshooting","Independent and flexible","Technically skilled"],
    weaknesses: ["Reserved and private","Easily bored","Insensitive to feelings","Dislikes commitment","Can be unpredictable"],
    in_love: "ISTPs are independent partners who express love through action, not words. They need space and can't stand clinginess. They're deeply loyal when they choose to commit.",
    as_a_friend: "The friend who fixes things without being asked and never needs recognition for it. Cool, calm, and dependable.",
    career: "Thrives in engineering, mechanics, carpentry, software development, forensic science, and athletics.",
    best_matches: ["ESFJ","ESTJ","ENFJ","ENTJ"],
    famous: ["Clint Eastwood","Michael Jordan","Bruce Lee","Steve Jobs (pre-CEO)"],
  },
  ISFP: {
    type: "ISFP", nickname: "The Adventurer", role: "Explorer",
    description: "ISFPs are gentle, artistic souls who live fully in the present. They're deeply sensitive, intensely creative, and quietly passionate about beauty, nature, and authentic experience.",
    strengths: ["Artistic and creative","Empathetic and warm","Flexible and open-minded","Passionate and spontaneous","Observant and curious"],
    weaknesses: ["Fiercely private","Difficulty with planning","Easily stressed","Avoids conflict","Struggles with criticism"],
    in_love: "ISFPs are tender, devoted partners who express love through creativity and small gestures. They need a partner who appreciates them as-is and doesn't try to change them.",
    as_a_friend: "The friend who brings unexpected beauty to ordinary moments. Non-judgmental, warm, and quietly attentive.",
    career: "Thrives in art, music, fashion, photography, cooking, physical therapy, and veterinary medicine.",
    best_matches: ["ESFJ","ESTJ","ENFJ","ENTJ"],
    famous: ["Frida Kahlo","Michael Jackson","Lana Del Rey","David Bowie"],
  },
  ESTP: {
    type: "ESTP", nickname: "The Entrepreneur", role: "Explorer",
    description: "ESTPs are energetic action-takers who live on the edge of possibility. Charming, bold, and perceptive, they make things happen in real time and thrive in fast-moving environments.",
    strengths: ["Bold and direct","Highly perceptive","Energetic and sociable","Excellent in crisis","Practical and resourceful"],
    weaknesses: ["Impulsive","Impatient","Risk-prone","Insensitive at times","Dislikes theory and planning"],
    in_love: "ESTPs are exciting, passionate partners who keep relationships dynamic. They need physical chemistry and freedom. They're direct about feelings but need space to roam.",
    as_a_friend: "The friend who turns any night into a story. Energizing, fun, always up for anything.",
    career: "Thrives in sales, entrepreneurship, first responder roles, sports, trading, and real estate.",
    best_matches: ["ISFJ","ISTJ","INFJ","INTJ"],
    famous:["Donald Trump","Ernest Hemingway","Madonna","Eddie Murphy"],
  },
  ESFP: {
    type: "ESFP", nickname: "The Entertainer", role: "Explorer",
    description: "ESFPs are spontaneous, energetic, and enthusiastic entertainers who make everything more fun. They live in the moment, love people, and have a natural gift for bringing joy to those around them.",
    strengths: ["Bold and original","Excellent people skills","Observant","Practical and resourceful","Entertaining and fun"],
    weaknesses: ["Easily bored","Poor long-term planning","Highly sensitive","Conflict-avoidant","Easily distracted"],
    in_love: "ESFPs are warm, affectionate, and fun-loving partners. They need excitement, laughter, and physical affection. They're deeply in tune with their partner's emotional needs.",
    as_a_friend: "The life of every party. Warm, funny, and the first to notice if something is off with you.",
    career: "Thrives in performing arts, hospitality, sales, childcare, event planning, and healthcare.",
    best_matches: ["ISFJ","ISTJ","INFJ","INTJ"],
    famous: ["Marilyn Monroe","Jamie Oliver","Adele","Will Smith"],
  },
};

export const ALL_TYPES = Object.keys(MBTI_DATA);

export const ROLE_COLOR: Record<string, string> = {
  Analyst: "#818cf8",
  Diplomat: "#34d399",
  Sentinel: "#60a5fa",
  Explorer: "#f97316",
};
